
# HealthPilot Phase-1 Clinical Intake Upgrade
# Generated by ChatGPT

import streamlit as st
from langchain_community.llms import Ollama
from rag_helper import retrieve_context
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import tempfile
from datetime import datetime

st.set_page_config(page_title="HealthPilot AI", page_icon="🩺", layout="wide")

st.markdown("""
<style>
.stApp {background-color:#F6F9FC;}
.big-title {font-size:48px;font-weight:800;color:#1565C0;}
.subtitle{color:#607D8B;font-size:17px;margin-bottom:18px;}
.workflow {background:#E3F2FD;padding:12px;border-radius:12px;border-left:5px solid #1976D2;font-size:16px;font-weight:600;margin-bottom:15px;}
.final-card{background:#E8F5E9;border-left:6px solid #2E7D32;padding:22px;border-radius:14px;margin-top:15px;box-shadow:0 4px 12px rgba(0,0,0,0.08);}
.badge-red{background:#D32F2F;color:white;padding:6px 12px;border-radius:20px;font-weight:700;display:inline-block;margin:4px;}
.badge-orange{background:#F57C00;color:white;padding:6px 12px;border-radius:20px;font-weight:700;display:inline-block;margin:4px;}
.badge-green{background:#2E7D32;color:white;padding:6px 12px;border-radius:20px;font-weight:700;display:inline-block;margin:4px;}
.stButton>button {
background-color:#00897B !important;color:white !important;border-radius:12px;
height:3.2em;width:100%;font-size:18px;font-weight:700;border:none;}
</style>
""", unsafe_allow_html=True)

llm = Ollama(model="mistral")

if "running" not in st.session_state:
    st.session_state.running = False

def create_pdf(patient, final_text):
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(tmp.name)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph("HealthPilot AI Clinical Summary", styles['Title']))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['BodyText']))
    story.append(Spacer(1,12))
    story.append(Paragraph("<b>Patient Information</b>", styles['Heading2']))
    story.append(Paragraph(patient.replace("\n","<br/>"), styles['BodyText']))
    story.append(Spacer(1,10))
    story.append(Paragraph("<b>Final Guidance</b>", styles['Heading2']))
    story.append(Paragraph(final_text.replace("\n","<br/>"), styles['BodyText']))
    doc.build(story)
    return tmp.name

st.markdown('<div class="big-title">🩺 HealthPilot AI</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Clinical Intake + Vitals + Multi-Agent Healthcare Workflow</div>', unsafe_allow_html=True)

with st.sidebar:
    st.header("⚙️ HealthPilot Control Center")
    st.success("🟢 Local AI Running")
    st.info("Model: Mistral")
    st.markdown("""
🧠 Planner Agent  
🖼️ Vision Agent  
📚 Retriever Agent  
🩺 Triage Agent  
🏥 Clinical Governance Agent
""")

col1, col2 = st.columns([1,1.35])

with col1:
    st.subheader("📋 Patient Intake Form")

    name = st.text_input("Patient Name","Rajesh Kumar")
    gender = st.selectbox("Gender",["Male","Female","Other"])
    age = st.number_input("Age",1,120,55)
    weight = st.number_input("Weight (kg)",20,250,75)
    temperature = st.number_input(
        "Temperature (°F)",
        90.0,
        110.0,
        102.2
    )
    spo2 = st.number_input(
        "SpO2 (%)",
        50,
        100,
        91
    )

    symptoms = st.text_area(
        "Symptoms",
        "fever, cough, breathing difficulty"
    )
    duration = st.text_input("Duration","3 days")
    conditions = st.text_input("Existing Conditions","diabetes")

    uploaded_file = st.file_uploader("🖼️ Upload Medical Image", type=["png","jpg","jpeg"])

    if uploaded_file:
        st.image(uploaded_file, width=250)

    analyze = st.button(
        "🧠 Run HealthPilot Analysis",
        disabled=st.session_state.running,
        type="primary"
    )

with col2:
    st.subheader("🏥 HealthPilot Analysis")
    st.markdown('<div class="workflow">🧠 Plan → 🖼️ Vision → 📚 Retrieve → 🩺 Triage → 🏥 Govern → ✅ Synthesize</div>', unsafe_allow_html=True)

    if analyze:
        st.session_state.running = True

    if st.session_state.running:

        fever_flag = "High Fever" if temperature > 102 else "Fever" if temperature > 100.4 else "Normal"
        spo2_flag = "Urgent" if spo2 < 92 else "Caution" if spo2 < 95 else "Normal"

        patient = f"""
Name: {name}
Gender: {gender}
Age: {age}
Weight: {weight} kg
Temperature: {temperature}°F ({fever_flag})
SpO2: {spo2}% ({spo2_flag})
Symptoms: {symptoms}
Duration: {duration}
Conditions: {conditions}
"""

        with st.spinner("HealthPilot reasoning..."):

            planner = """1. Understand symptoms
2. Review uploaded image
3. Retrieve medical guidance
4. Evaluate vitals
5. Perform educational triage
6. Governance review
7. Final synthesis"""

            vision_note = "No image uploaded."
            if uploaded_file:
                vision_note = "Image uploaded. Educational review suggested."

            context = retrieve_context(patient + vision_note)

            triage = llm.invoke(f"""
Patient:
{patient}

Knowledge:
{context}

Give concise bullets:
- Symptom Summary
- Possible Category
- Suggested Urgency
- Safety Guidance
""")

            governance = llm.invoke(f"""
Review safely.

Triage:
{triage}

Vitals:
Temperature={temperature}
SpO2={spo2}

Provide concise governance bullets.
""")

            temp_badge = "badge-red" if fever_flag=="High Fever" else "badge-orange" if fever_flag=="Fever" else "badge-green"
            spo2_badge = "badge-red" if spo2_flag=="Urgent" else "badge-orange" if spo2_flag=="Caution" else "badge-green"

            final_summary = f"""
👤 Patient Profile
• {name}
• {gender}, {age} years
• Weight: {weight} kg

🌡 Vital Signs
• Temperature: {temperature}°F ({fever_flag})
• SpO2: {spo2}% ({spo2_flag})

🏥 Clinical Guidance
{governance}

⚠ Educational AI only. Doctor review required.
"""

            with st.expander("🧠 Planner Agent", expanded=True):
                st.markdown(planner)

            with st.expander("🖼️ Vision Agent"):
                st.info(vision_note)

            with st.expander("📚 Retriever Agent"):
                st.markdown(context)

            with st.expander("🩺 Triage Agent"):
                st.markdown(triage)

            with st.expander("🏥 Clinical Governance Agent"):
                st.markdown(governance)

            st.markdown(f"""
<div class="final-card">
<h3>✅ HealthPilot Final Guidance</h3>

<h4>👤 Patient Profile</h4>
<ul>
<li>{name}</li>
<li>{gender}, {age} years</li>
<li>{weight} kg</li>
</ul>

<h4>🌡 Vital Risk Status</h4>
<div class="{temp_badge}">{fever_flag} • {temperature}°F</div>
<div class="{spo2_badge}">SpO2 {spo2}% • {spo2_flag}</div>

<h4>🏥 Clinical Guidance</h4>
<pre style="white-space: pre-wrap;">{governance}</pre>

<p><b>⚠ Educational AI only. Doctor review required.</b></p>
</div>
""", unsafe_allow_html=True)

            pdf_path = create_pdf(patient, final_summary)

            with open(pdf_path, "rb") as f:
                st.download_button(
                    "📄 Download Clinical Summary PDF",
                    f,
                    file_name="HealthPilot_Clinical_Summary.pdf",
                    mime="application/pdf"
                )

        st.session_state.running = False